plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bocchi.pinkchan.shimeji'
    compileSdk 34

    defaultConfig {
        applicationId "com.bocchi.pinkchan.shimeji"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Zero dependencias externas: usa componentes puros de Android SDK para máxima fluidez y bajo consumo de batería
}
